# Generated by Django 4.2.7 on 2025-08-10 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_about_personalinfo_sociallink"),
    ]

    operations = []
