# Generated by Django 4.2.7 on 2025-08-10 11:13

from django.db import migrations


def populate_skills(apps, schema_editor):
    Skill = apps.get_model('api', 'Skill')
    
    # Programming Languages
    skills_data = [
        # Programming Languages
        {'name': 'Python', 'category': 'programming', 'level': 95, 'icon': '🐍'},
        {'name': 'JavaScript', 'category': 'programming', 'level': 90, 'icon': '⚡'},
        {'name': 'TypeScript', 'category': 'programming', 'level': 85, 'icon': '🔷'},
        {'name': 'Java', 'category': 'programming', 'level': 80, 'icon': '☕'},
        {'name': 'C++', 'category': 'programming', 'level': 75, 'icon': '⚙️'},
        {'name': 'SQL', 'category': 'programming', 'level': 88, 'icon': '🗃️'},
        
        # Machine Learning & AI
        {'name': 'TensorFlow', 'category': 'ml_ai', 'level': 90, 'icon': '🧠'},
        {'name': 'PyTorch', 'category': 'ml_ai', 'level': 85, 'icon': '🔥'},
        {'name': 'Scikit-learn', 'category': 'ml_ai', 'level': 92, 'icon': '📊'},
        {'name': 'OpenCV', 'category': 'ml_ai', 'level': 80, 'icon': '👁️'},
        {'name': 'NLP', 'category': 'ml_ai', 'level': 85, 'icon': '💬'},
        {'name': 'Deep Learning', 'category': 'ml_ai', 'level': 88, 'icon': '🔗'},
        {'name': 'Computer Vision', 'category': 'ml_ai', 'level': 83, 'icon': '📷'},
        
        # Web Development
        {'name': 'React.js', 'category': 'web_dev', 'level': 92, 'icon': '⚛️'},
        {'name': 'Next.js', 'category': 'web_dev', 'level': 85, 'icon': '▲'},
        {'name': 'Django', 'category': 'web_dev', 'level': 90, 'icon': '🎯'},
        {'name': 'Flask', 'category': 'web_dev', 'level': 88, 'icon': '🌶️'},
        {'name': 'Node.js', 'category': 'web_dev', 'level': 85, 'icon': '🚀'},
        {'name': 'HTML/CSS', 'category': 'web_dev', 'level': 95, 'icon': '🎨'},
        {'name': 'Tailwind CSS', 'category': 'web_dev', 'level': 90, 'icon': '💨'},
        
        # Data Science & Analytics
        {'name': 'Pandas', 'category': 'data_science', 'level': 95, 'icon': '🐼'},
        {'name': 'NumPy', 'category': 'data_science', 'level': 93, 'icon': '🔢'},
        {'name': 'Matplotlib', 'category': 'data_science', 'level': 88, 'icon': '📈'},
        {'name': 'Seaborn', 'category': 'data_science', 'level': 85, 'icon': '🌊'},
        {'name': 'Jupyter', 'category': 'data_science', 'level': 92, 'icon': '📔'},
        {'name': 'Data Visualization', 'category': 'data_science', 'level': 87, 'icon': '📊'},
        
        # Tools & Technologies
        {'name': 'Git & GitHub', 'category': 'tools', 'level': 90, 'icon': '🔧'},
        {'name': 'Docker', 'category': 'tools', 'level': 75, 'icon': '🐳'},
        {'name': 'AWS', 'category': 'tools', 'level': 70, 'icon': '☁️'},
        {'name': 'PostgreSQL', 'category': 'tools', 'level': 85, 'icon': '🐘'},
        {'name': 'MongoDB', 'category': 'tools', 'level': 80, 'icon': '🍃'},
        {'name': 'REST APIs', 'category': 'tools', 'level': 90, 'icon': '🔗'},
        {'name': 'Linux', 'category': 'tools', 'level': 82, 'icon': '🐧'},
    ]
    
    for skill_data in skills_data:
        Skill.objects.get_or_create(**skill_data)


def reverse_populate_skills(apps, schema_editor):
    Skill = apps.get_model('api', 'Skill')
    Skill.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_populate_content"),
    ]

    operations = [
        migrations.RunPython(populate_skills, reverse_populate_skills),
    ]
