# Generated by Django 4.2.7 on 2025-08-10 11:14

from django.db import migrations
from django.utils import timezone


def populate_sample_contacts(apps, schema_editor):
    Contact = apps.get_model('api', 'Contact')
    
    # Sample contact messages
    contacts_data = [
        {
            'name': 'Sarah Johnson',
            'email': 'sarah.johnson@techcorp.com',
            'subject': 'ML Project Collaboration',
            'message': 'Hi Jenish, I came across your portfolio and was impressed by your machine learning projects. We have an exciting opportunity for a computer vision project and would love to discuss potential collaboration. Looking forward to hearing from you!',
            'created_at': timezone.now() - timezone.timedelta(days=2),
            'is_read': False
        },
        {
            'name': 'David Martinez',
            'email': 'david.m@startup.io',
            'subject': 'Full-Stack Developer Position',
            'message': 'Hello Jenish, We are a growing startup looking for a full-stack developer with AI/ML expertise. Your portfolio shows exactly the kind of skills we need. Would you be interested in a quick call to discuss this opportunity?',
            'created_at': timezone.now() - timezone.timedelta(days=5),
            'is_read': True
        },
        {
            'name': 'Dr. Emily Chen',
            'email': 'emily.chen@university.edu',
            'subject': 'Research Collaboration Opportunity',
            'message': 'Dear Jenish, I am a research professor at the university and I am impressed by your NLP and deep learning work. We have a research project on natural language processing that might interest you. Could we schedule a meeting to discuss?',
            'created_at': timezone.now() - timezone.timedelta(days=1),
            'is_read': False
        },
        {
            'name': 'Alex Thompson',
            'email': 'alex@dataanalytics.com',
            'subject': 'Freelance Data Science Project',
            'message': 'Hi Jenish, We have a short-term data science project involving customer behavior analysis. Your experience with pandas and scikit-learn makes you a perfect fit. The project duration is 2-3 weeks. Are you available for freelance work?',
            'created_at': timezone.now() - timezone.timedelta(hours=6),
            'is_read': False
        },
        {
            'name': 'Rachel Kumar',
            'email': 'rachel.kumar@techsolutions.com',
            'subject': 'Portfolio Website Development',
            'message': 'Hello! I love your portfolio design and would like to hire you to create a similar portfolio website for our team. Could you provide a quote for developing a React-based portfolio with admin panel functionality?',
            'created_at': timezone.now() - timezone.timedelta(days=3),
            'is_read': True
        }
    ]
    
    for contact_data in contacts_data:
        Contact.objects.get_or_create(
            email=contact_data['email'],
            subject=contact_data['subject'],
            defaults=contact_data
        )


def reverse_populate_contacts(apps, schema_editor):
    Contact = apps.get_model('api', 'Contact')
    # Only delete sample contacts, not real ones that might come from the form
    sample_emails = [
        'sarah.johnson@techcorp.com',
        'david.m@startup.io', 
        'emily.chen@university.edu',
        'alex@dataanalytics.com',
        'rachel.kumar@techsolutions.com'
    ]
    Contact.objects.filter(email__in=sample_emails).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_auto_20250810_1643"),
    ]

    operations = [
        migrations.RunPython(populate_sample_contacts, reverse_populate_contacts),
    ]
