# Generated by Django 4.2.7 on 2025-08-10 11:18

from django.db import migrations
from django.utils import timezone
from datetime import date


def update_fresher_profile(apps, schema_editor):
    PersonalInfo = apps.get_model('api', 'PersonalInfo')
    About = apps.get_model('api', 'About')
    Experience = apps.get_model('api', 'Experience')
    Education = apps.get_model('api', 'Education')
    Project = apps.get_model('api', 'Project')
    Contact = apps.get_model('api', 'Contact')
    
    # Update Personal Information for fresher seeking internships
    personal_info, created = PersonalInfo.objects.get_or_create(
        defaults={
            'name': 'Jenish Barvaliya',
            'title': 'Information Technology Student',
            'subtitle': 'Seeking Internships in Machine Learning & Artificial Intelligence',
            'location': 'Surat, Gujarat, India',
            'email': 'jenishbarvaliya2012@gmail.com',
            'phone': '+91 9510007247',
            'linkedin': 'https://linkedin.com/in/jenish-barvaliya-4b5312369',
            'github': 'https://github.com/jenish2917',
            'resume': '',
            'is_active': True
        }
    )
    
    if not created:
        personal_info.name = 'Jenish Barvaliya'
        personal_info.title = 'Information Technology Student'
        personal_info.subtitle = 'Seeking Internships in Machine Learning & Artificial Intelligence'
        personal_info.location = 'Surat, Gujarat, India'
        personal_info.email = 'jenishbarvaliya2012@gmail.com'
        personal_info.phone = '+91 9510007247'
        personal_info.linkedin = 'https://linkedin.com/in/jenish-barvaliya-4b5312369'
        personal_info.github = 'https://github.com/jenish2917'
        personal_info.save()
    
    # Update About section for fresher profile
    about, created = About.objects.get_or_create(
        defaults={
            'summary': """Motivated Information Technology student in 8th semester with a strong passion for Machine Learning and Artificial Intelligence. 
            Currently pursuing B.Tech in IT with 9.34/10.0 CGPA and seeking internship opportunities to apply theoretical knowledge in real-world ML/AI projects. 
            Proficient in Python, TensorFlow, and data science libraries with hands-on experience in developing ML models through academic projects. 
            Eager to contribute to innovative AI solutions while learning from industry professionals in a collaborative environment.""",
            
            'vision': """To secure an internship in Machine Learning and Artificial Intelligence where I can apply my academic knowledge, 
            contribute to meaningful projects, and gain practical industry experience that will help me grow into a skilled AI/ML professional.""",
            
            'highlights': [
                "8th Semester B.Tech IT Student with 9.34/10.0 CGPA",
                "Strong foundation in Python, Machine Learning, and Data Science",
                "Academic projects in NLP, Recommendation Systems, and Predictive Analytics",
                "Seeking internships in Machine Learning and Artificial Intelligence",
                "Proficient in TensorFlow, Scikit-learn, and modern ML frameworks",
                "Passionate about AI-driven solutions and continuous learning"
            ],
            'is_active': True
        }
    )
    
    if not created:
        about.summary = """Motivated Information Technology student in 8th semester with a strong passion for Machine Learning and Artificial Intelligence. 
        Currently pursuing B.Tech in IT with 9.34/10.0 CGPA and seeking internship opportunities to apply theoretical knowledge in real-world ML/AI projects. 
        Proficient in Python, TensorFlow, and data science libraries with hands-on experience in developing ML models through academic projects. 
        Eager to contribute to innovative AI solutions while learning from industry professionals in a collaborative environment."""
        
        about.vision = """To secure an internship in Machine Learning and Artificial Intelligence where I can apply my academic knowledge, 
        contribute to meaningful projects, and gain practical industry experience that will help me grow into a skilled AI/ML professional."""
        
        about.highlights = [
            "8th Semester B.Tech IT Student with 9.34/10.0 CGPA",
            "Strong foundation in Python, Machine Learning, and Data Science", 
            "Academic projects in NLP, Recommendation Systems, and Predictive Analytics",
            "Seeking internships in Machine Learning and Artificial Intelligence",
            "Proficient in TensorFlow, Scikit-learn, and modern ML frameworks",
            "Passionate about AI-driven solutions and continuous learning"
        ]
        about.save()
    
    # Clear existing work experience (as you're a fresher)
    Experience.objects.all().delete()
    
    # Update Education to reflect current status
    education, created = Education.objects.get_or_create(
        degree="Bachelor of Technology (B.Tech) in Information Technology",
        defaults={
            'institution': 'Sarvajanik College of Engineering and Technology',
            'location': 'Surat, Gujarat, India',
            'start_date': date(2022, 8, 1),  # Assuming started in Aug 2022
            'end_date': date(2026, 5, 31),   # Expected graduation May 2026
            'is_current': True,
            'gpa': '9.34/10.0',
            'description': 'Currently in 8th semester pursuing B.Tech in Information Technology with specialization in Machine Learning and Data Science. Maintaining excellent academic performance while working on practical ML/AI projects.',
            'coursework': [
                'Machine Learning',
                'Artificial Intelligence', 
                'Data Structures and Algorithms',
                'Database Management Systems',
                'Software Engineering',
                'Web Technologies',
                'Computer Networks',
                'Operating Systems',
                'Natural Language Processing',
                'Data Mining and Analytics'
            ]
        }
    )
    
    if not created:
        education.start_date = date(2022, 8, 1)
        education.end_date = date(2026, 5, 31)
        education.is_current = True
        education.gpa = '9.34/10.0'
        education.description = 'Currently in 8th semester pursuing B.Tech in Information Technology with specialization in Machine Learning and Data Science. Maintaining excellent academic performance while working on practical ML/AI projects.'
        education.coursework = [
            'Machine Learning',
            'Artificial Intelligence',
            'Data Structures and Algorithms', 
            'Database Management Systems',
            'Software Engineering',
            'Web Technologies',
            'Computer Networks',
            'Operating Systems',
            'Natural Language Processing',
            'Data Mining and Analytics'
        ]
        education.save()
    
    # Update project descriptions to reflect academic projects
    projects_updates = [
        {
            'title': 'Fantasy Cricket Team Predictor',
            'description': 'Academic project developing ML recommendation engine for Dream11 fantasy teams with ensemble learning approach',
            'long_description': 'Comprehensive academic project demonstrating machine learning skills through sports analytics. Built as part of coursework to understand real-world ML applications.',
            'status': 'completed'
        },
        {
            'title': 'Spam Detection Classifier',
            'description': 'Academic NLP project implementing multi-class spam detection using TF-IDF vectorization and supervised learning',
            'long_description': 'Academic project focused on natural language processing and text classification. Implemented as part of ML coursework to understand NLP techniques.',
            'status': 'completed'
        },
        {
            'title': 'Movie Recommendation System',
            'description': 'Academic project implementing collaborative filtering algorithms for personalized movie recommendations',
            'long_description': 'Academic project exploring recommendation systems and collaborative filtering techniques. Built to understand matrix factorization and similarity algorithms.',
            'status': 'completed'
        }
    ]
    
    for project_update in projects_updates:
        try:
            project = Project.objects.get(title=project_update['title'])
            project.description = project_update['description']
            project.long_description = project_update['long_description']
            project.status = project_update['status']
            project.save()
        except Project.DoesNotExist:
            pass
    
    # Update contact messages to reflect internship inquiries
    Contact.objects.all().delete()
    
    internship_contacts = [
        {
            'name': 'Sarah Martinez',
            'email': 'sarah.martinez@techcorp.com',
            'subject': 'ML Internship Opportunity - Summer 2025',
            'message': 'Hi Jenish, We came across your academic projects and were impressed by your ML work, especially the fantasy cricket predictor. We have summer internship openings in our AI team and would love to discuss opportunities for talented students like you.',
            'created_at': timezone.now() - timezone.timedelta(days=2),
            'is_read': False
        },
        {
            'name': 'Dr. Raj Patel',
            'email': 'raj.patel@researchlab.in',
            'subject': 'Research Internship - NLP Lab',
            'message': 'Dear Jenish, Your spam detection project shows great potential in NLP. We offer research internships in our NLP lab for final year students. This could be perfect for your 8th semester internship requirement.',
            'created_at': timezone.now() - timezone.timedelta(days=1),
            'is_read': False
        },
        {
            'name': 'Priya Sharma',
            'email': 'priya@aistartupin.com',
            'subject': 'AI Internship for College Students',
            'message': 'Hello Jenish, We are a growing AI startup offering internships to final year students. Your academic projects demonstrate strong ML fundamentals. We would like to discuss internship opportunities that align with your career goals.',
            'created_at': timezone.now() - timezone.timedelta(hours=12),
            'is_read': False
        },
        {
            'name': 'David Kumar',
            'email': 'david@datasciencefirm.co',
            'subject': 'Data Science Internship Program',
            'message': 'Hi Jenish, Your movie recommendation system caught our attention. We have a structured 6-month internship program for students in their final year. This would be perfect for your 8th semester internship requirements.',
            'created_at': timezone.now() - timezone.timedelta(hours=6),
            'is_read': False
        },
        {
            'name': 'Emily Thompson',
            'email': 'emily@mltechsolutions.com',
            'subject': 'Final Year Internship - ML Engineer Track',
            'message': 'Dear Jenish, We offer specialized internships for final year IT students interested in ML careers. Your 9.34 CGPA and project portfolio make you an ideal candidate for our ML engineer track internship program.',
            'created_at': timezone.now() - timezone.timedelta(hours=3),
            'is_read': False
        }
    ]
    
    for contact_data in internship_contacts:
        Contact.objects.create(**contact_data)


def reverse_fresher_update(apps, schema_editor):
    # This function would restore the previous state
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_auto_20250810_1645"),
    ]

    operations = [
        migrations.RunPython(update_fresher_profile, reverse_fresher_update),
    ]
