# Generated by Django 4.2.7 on 2025-08-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_auto_20250810_1648"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="profile_image",
            field=models.URLField(blank=True, default="/images/profile.jpg"),
        ),
    ]
